# Conexión directa a MySQL en Railway
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:48005/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=quOqZMpzfFkvNvswrrRHdCLZcVtYqgse
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true